<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $now = now();
        DB::table('categories')->insert([
            [
                'user_id' => null,
                'name' => 'Food & Beverage',
                'type' => 'expense',
                'icon' => 'utensils',
                'color' => '#f97316',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Bills & Utilities',
                'type' => 'expense',
                'icon' => 'file-invoice-dollar',
                'color' => '#64748b',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Phone Bill',
                'type' => 'expense',
                'icon' => 'phone',
                'color' => '#0ea5e9',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Water Bill',
                'type' => 'expense',
                'icon' => 'droplet',
                'color' => '#3b82f6',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Electricity Bill',
                'type' => 'expense',
                'icon' => 'bolt',
                'color' => '#eab308',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Gas Bill',
                'type' => 'expense',
                'icon' => 'fire',
                'color' => '#f97316',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Television Bill',
                'type' => 'expense',
                'icon' => 'tv',
                'color' => '#8b5cf6',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Internet Bill',
                'type' => 'expense',
                'icon' => 'wifi',
                'color' => '#14b8a6',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Rentals',
                'type' => 'expense',
                'icon' => 'home',
                'color' => '#ec4899',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Other Utility Bills',
                'type' => 'expense',
                'icon' => 'file-invoice',
                'color' => '#94a3b8',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Shopping',
                'type' => 'expense',
                'icon' => 'shopping-cart',
                'color' => '#d946ef',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Personal Items',
                'type' => 'expense',
                'icon' => 'user',
                'color' => '#6366f1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Houseware',
                'type' => 'expense',
                'icon' => 'couch',
                'color' => '#84cc16',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Makeup',
                'type' => 'expense',
                'icon' => 'gem',
                'color' => '#f43f5e',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Family',
                'type' => 'expense',
                'icon' => 'users',
                'color' => '#10b981',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Home Maintenance',
                'type' => 'expense',
                'icon' => 'tools',
                'color' => '#b45309',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Home Services',
                'type' => 'expense',
                'icon' => 'hands-helping',
                'color' => '#06b6d4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Pets',
                'type' => 'expense',
                'icon' => 'dog',
                'color' => '#854d0e',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Transportation',
                'type' => 'expense',
                'icon' => 'car',
                'color' => '#0284c7',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Vehicle Maintenance',
                'type' => 'expense',
                'icon' => 'wrench',
                'color' => '#475569',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Health & Fitness',
                'type' => 'expense',
                'icon' => 'heartbeat',
                'color' => '#ef4444',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Medical Check-up',
                'type' => 'expense',
                'icon' => 'stethoscope',
                'color' => '#06b6d4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Fitness',
                'type' => 'expense',
                'icon' => 'dumbbell',
                'color' => '#6366f1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Education',
                'type' => 'expense',
                'icon' => 'graduation-cap',
                'color' => '#3b82f6',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Entertainment',
                'type' => 'expense',
                'icon' => 'gamepad',
                'color' => '#8b5cf6',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Streaming Service',
                'type' => 'expense',
                'icon' => 'play-circle',
                'color' => '#ef4444',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Fun Money',
                'type' => 'expense',
                'icon' => 'laugh-beam',
                'color' => '#f59e0b',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Gifts & Donations',
                'type' => 'expense',
                'icon' => 'gift',
                'color' => '#ec4899',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Insurances',
                'type' => 'expense',
                'icon' => 'shield-alt',
                'color' => '#10b981',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Investment',
                'type' => 'expense',
                'icon' => 'chart-line',
                'color' => '#10b981',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Other Expense',
                'type' => 'expense',
                'icon' => 'ellipsis-h',
                'color' => '#6b7280',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Outgoing transfer',
                'type' => 'expense',
                'icon' => 'arrow-left',
                'color' => '#3b82f6',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Pay Interest',
                'type' => 'expense',
                'icon' => 'percentage',
                'color' => '#f43f5e',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::table('categories')->where('type', 'expense')->whereIn('name', [
            'Food & Beverage',
            'Bills & Utilities',
            'Phone Bill',
            'Water Bill',
            'Electricity Bill',
            'Gas Bill',
            'Television Bill',
            'Internet Bill',
            'Rentals',
            'Other Utility Bills',
            'Shopping',
            'Personal Items',
            'Houseware',
            'Makeup',
            'Family',
            'Home Maintenance',
            'Home Services',
            'Pets',
            'Transportation',
            'Vehicle Maintenance',
            'Health & Fitness',
            'Medical Check-up',
            'Fitness',
            'Education',
            'Entertainment',
            'Streaming Service',
            'Fun Money',
            'Gifts & Donations',
            'Insurances',
            'Investment',
            'Other Expense',
            'Outgoing transfer',
            'Pay Interest',
        ])->delete();
    }
};
